import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import "lenis/dist/lenis.css";
import { LenisProvider } from "./_components/Providers/lenis-provider";
import ScrollAnimations from "./_components/Providers/ScrollAnimations";

const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.variable} h-full `}>
      <body className="relative flex flex-col ">
        <LenisProvider>
          <ScrollAnimations>{children}</ScrollAnimations>
        </LenisProvider>
      </body>
    </html>
  );
}
