import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "lenis/dist/lenis.css";
import { LenisProvider } from "./_components/Providers/lenis-provider";
import ScrollAnimations from "./_components/Providers/ScrollAnimations";

const thmanyah = localFont({
  src: [
    { path: "../public/fonts/thmanyahsans-Light.otf", weight: "300" },
    { path: "../public/fonts/thmanyahsans-Regular.otf", weight: "400" },
    { path: "../public/fonts/thmanyahsans-Medium.otf", weight: "500" },
    { path: "../public/fonts/thmanyahsans-Bold.otf", weight: "700" },
    { path: "../public/fonts/thmanyahsans-Black.otf", weight: "900" },
  ],
  variable: "--font-thmanyah",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${thmanyah.variable} h-full `}>
      <body className="relative flex flex-col ">
        <LenisProvider>
          <ScrollAnimations>{children}</ScrollAnimations>
        </LenisProvider>
      </body>
    </html>
  );
}
